[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["cd server && npm install"]

[phases.build]
cmds = ["cd server && npm run build --if-present"]

[start]
cmd = "cd server && npm start"
